### ISSUE TITLE
eShop for .NET 8.0???

### ISSUE THREAD

**Issue by DynConcepts** [dotnet/eShop#268]
Any plans? [have I missed something?]

**Comment by danmoseley** [comment]
Hello, could you say more? Eshop in this repo runs on .NET 8.

**Comment by davidcorbin-atmosera** [comment]
@danmoseley - Thanks for getting back.... Will head into office in a few and see if I can pull more details... but here is the summary:
1) Windows 11 VM [Hyper-V]
2) VS-2022 17.8.4
3) .NET 8.0 SDK [8.0.203]

Open Solution i[eShop.Web.slnf]   in Visual Studio - got lots of errors.... 

Good to know that it should work .. I will dig in a bit and get back ASAP.

**Comment by davidcorbin-atmosera** [comment]
Interesting... After I spent time with this yesterday, I tried a number of other samples [such as the CommunityToolKit] and ran into various problems, which resulted in the installing of some additional components, and also necessitated the removal of my .nuget\packages directory 

Apparently (for those other items) the existant of an older version of some packages that met the dependency requirements were preventing the restoration of the latest, and that led to a bunch of rabbit holes...

So just now I tried eShop again... This time simple command line...

![image](https://github.com/dotnet/eShop/assets/83300052/af393c88-b70a-4910-852c-b0396d9deece)

While this allowed the resources page to show, selecting the actual WebApplication continued do have timeouts...

![Screenshot 2024-03-29 112101](https://github.com/dotnet/eShop/assets/83300052/4370f2e5-cb94-4025-8241-2116ac1dd6a7)

I will continue to try to debug, since it now seems the overall environment is somewhat alive, and this is something that is supposed to work. [The number of projects impacted by the RID and other MAUI related changes, that even Upgrade did not fix is significant - based on just small experience, possibly the least backwards compatible set of changes [.Net, not eShop] that I have seen in a very long time =- and I am old]

**Comment by davidcorbin-atmosera** [comment]
Hope eve4ryone had a good weekend... Fired up machine this morning (it had rebooted for an update, apparently)... And seeing different symptoms...
Apphost (from dotnet commandline) seems to start ok... but "Cant Reach Page [ERR_CONNECTION_REFUSED] attempting to access http://[localhost](http://localhost:5045/):5045/....

**Comment by adityamandaleeka** [comment]
@davidcorbin-atmosera I haven't seen these issues on my end, but can you try the latest? We've updated the main branch to Aspire preview 5.

**Comment by jamesmontemagno** [comment]
Haven't seen this here either. Let us know if you see this in latest, else will close out.
