### ISSUE TITLE
Required Clarification on Catalog.API

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/eShop#93]
Hi @davidfowl ,
I was walking through the Catalog.API code. In this file https://github.com/dotnet/eShop/blob/main/src/Catalog.API/Apis/CatalogApi.cs I see a usage of `[AsParameters] CatalogServices services` as a second parameter in all methods. I'm at loss to understand where CatalogServices  is getting constructed. It is neither created in DI nor coming as a param. Can you please clarify?

**Comment by davidfowl** [comment]
CatalogServices is a normal class and [AsParameters] says "treat these properties like they are arguments to this method". This is a feature that's been in minimal API since .NET 7 (see https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0#parameter-binding-for-argument-lists-with-asparameters).

**Comment by VenkateshSrini** [comment]
Please clarify how it is instantiated and how values are passed. I don't see it coming from the http call. Also it is not in DI container also

**Comment by saptarshidas1809** [comment]
@VenkateshSrini, take a look at `GlobalUsings.cs` inside the Setup folder within `Catalog.API`. Here, you have a number of global using declarations. Haven't taken a closer look at this file, how it is configured, etc. but this could be a reason why you find no imports within `CatalogApi.cs`, since they are already defined and accessible from GlobalUsings. Notice how every directory has a `GlobalUsings.cs`. Probably kept to organize common imports in a single place.

**Comment by VenkateshSrini** [comment]
@saptarshidas1809 ,
If you could see my question earlier I have been asking as to how the `CatalogServices services` is getting instantiated even though it is not passed as a parameter

**Comment by VenkateshSrini** [comment]
@saptarshidas1809 ,
If you could see my question earlier I have been asking as to how the `CatalogServices services` is getting instantiated in the minimal api though I do not see any parameter that is getting passed

**Comment by VenkateshSrini** [comment]
@davidfowl Thanks I got the concept https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/minimal-apis/samples/arg-lists/Program.cs

**Comment by captainsafia** [comment]
@VenkateshSrini Glad you were able to get clarity on this.

For other who are reading this the `[AsParameters]` attribute in minimal APIs allows a user to opt-in to surrogate binding. So you can define a type like this:

```csharp
class SurrogateServices
{
  public IFooService FooService { get; set; }
  public IBarService BarService { get; set; }
}
```

And use it like so:

```csharp
app.MapPost("/", ([AsParameters] SurrogateServices services) => ...);
```

Then minimal APIs will expand the `SurrogateServices` type and bind `FooService` and `BarService` independently from the list.
